lfwsite/lfw/urls.py
from django.urls import path, include
from . import views


app_name = 'lfw' # for namespacing
urlpatterns = [
    path('', views.index, name='index'),
	path('jobappform/', views.jobappform, name='jobappform'),
	path('add_res/', views.add_res, name='add_res'),
	path('add_cl/', views.add_cl, name='add_cl'),
	path('display_jobappview/', views.display_jobappview, name='display_jobappview'),
	path('display_pipeline/', views.display_pipeline, name='display_pipeline'),
	path('display_canvas/', views.display_canvas, name='display_canvas'),
	path('display_lagging/', views.display_lagging, name='display_lagging'),
	path('lagging_json/', views.lagging_json, name='lagging_json'),
	path('canvas_json/', views.canvas_json, name='canvas_json'),
	path('elapsed_json/', views.elapsed_json, name='elapsed_json'),
	path('display_elapsed/', views.display_elapsed, name='display_elapsed'),
	path('clbuilder/', views.clbuilder, name='clbuilder'),
	path('skills_list/', views.clbuilder, name='skills_list'),
	path('add_skill/', views.skills_input, name='skills_input'),
	path('jobapp_loader/', views.jobapp_loader, name='jobapp_loader'),
	path('cltodo/', views.clbuilder, name='cltodo'),
	path('cllistview/', views.cllistview, name='cllistview'),
	path('jobapplistview/', views.jobapplistview, name='jobapplistview'),
	path('coverletter/edit/<int:pk>/', views.edit_coverletter, name='edit_coverletter'),
	path('edit_jobapp/<int:pk>/', views.edit_jobapp, name='edit_jobapp'),
	path('cllistview/', views.cllistview, name='cllistview'),
	path('jobappstatusupdate/<int:pk>/', views.move_jobapp_status, name='jobappstatusupdate'),
	path('coverlettertemplateselect/', views.coverlettertemplateselect, name='coverlettertemplateselect'),
	path('coverlettertext_loader/', views.coverlettertemplate_loader, name='coverlettertext_loader'),

]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

lfwsite/lfwsite/urls.py
from django.urls import path, include
from django.contrib import admin
from lfwsite import views

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('', include('lfw.urls')), # Note: all your app urls will start with this path
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
    path('registration/register/', views.register, name='register'),

]

lfwsite/lfw/forms.py
from datetime import datetime
from django import forms
from django.template import Template
from material import Layout, Row, Column, Fieldset, Span2, Span3, Span5, Span6, Span10
from django.forms import ModelForm
from .models import Jobapp, Resume, Coverletter, Contact, Skill

class Jobappform(forms.Form):
    name = forms.CharField(max_length=50)
    description = forms.CharField(required= False)
    company = forms.CharField(max_length=50, required= False)
    contact = forms.ModelChoiceField(queryset=None, required=False)
    url = forms.URLField(max_length=400, required=False)

    coverletter = forms.ModelChoiceField(queryset=None, required=False) 
    resume = forms.ModelChoiceField(queryset=None, required=False) 

    followup_touches = forms.IntegerField(required= False)
    first_contacted = forms.DateTimeField(required= False)
    last_contacted = forms.DateTimeField(required= False)
    date_foundbyuser = forms.DateTimeField(required= False)
    date_due = forms.DateTimeField(required= False)
    date_applied = forms.DateTimeField(required= False)
    date_created = forms.DateTimeField(required= False)

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user
        self.fields['contact'].queryset = Contact.objects.filter(user=user)
        self.fields['coverletter'].queryset = Coverletter.objects.filter(user=user)
        self.fields['resume'].queryset = Resume.objects.filter(user=user)
    
    layout = Layout('name', 'company', 'description',
                Row('coverletter', 'resume', 'url'),
                Row('first_contacted', 'last_contacted'),
                Row('date_foundbyuser', 'date_due', 'date_applied', 'date_created'))

class CoverletterForm(forms.Form):
    skills = forms.ModelMultipleChoiceField(queryset=None, widget=forms.CheckboxSelectMultiple)

    coverlettercopy = forms.CharField(widget=forms.Textarea(attrs={'class': 'coverlettertext'}))


    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user
        self.fields['skills'].queryset = Skill.objects.filter(user=user)

    # layout = Layout(

    #     )

class Resumeform(ModelForm):
    class Meta:
        model = Resume
        fields = ('url', 'name',)
class Clform(ModelForm):
    class Meta:
        model = Coverletter
        fields = ('url', 'name',)


class Skills_input(ModelForm):
    class Meta:
        model = Skill
        fields = ('name', 'copy',)


# class Jobappform(ModelForm):
#     class Meta:
#         # the model to associate with the form
#         model = Jobapp
#         # a list of all the models' fields you want in the form
#         exclude = ['user', 'followup_touches', 'first_contacted', 'last_contacted', 'date_due', 'date_applied','date_created']
#         widgets = {
#                  'resume': Select(lookups=['name__icontains']),
#                  'coverletter': Select(lookups=['name__icontains'])
#              }

#     layout = Layout(
#         Row('name'),
#         Row('company', 'referred_by'),
#         Row('description', 'url'),
#         Row('date_rolecreated'),
#         Row('coverletter', 'resume'))   

lfwsite/lfw/views.py
from django.core import serializers
from django.http import HttpResponse, HttpResponseRedirect, HttpRequest, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404, reverse
from .models import Jobapp, Resume, Coverletter, Skill, Coverlettertemplate
from .forms import Jobappform, Resumeform, Clform, Skills_input, CoverletterForm
from django.contrib.auth.decorators import permission_required, login_required
from django import forms

@login_required()
def index(request):
	return render(request,'lfw/index.html', status_context(request))

def display_jobappview(request):
	jobapps = Jobapp.objects.filter(user=request.user)
	fields = [f.name for f in Jobapp._meta.get_fields()]
	print(fields)
	return render(request,'lfw/jobappview.html', {'jobapps': jobapps, 'fields':fields})

def display_elapsed(request):
	pipeline_individual_count = Jobapp.objects.filter(user=request.user)
	return render(request,'lfw/display_elapsed.html', status_context(request))

def display_lagging(request):
	pipeline_individual_count = Jobapp.objects.filter(user=request.user)
	return render(request,'lfw/display_lagging.html', status_context(request))

def lagging_json(request):
	jobapps = serializers.serialize("json", Jobapp.objects.filter(user=request.user, pipeline_status='PS'))
	return JsonResponse(jobapps, safe=False) #this return could be redundant, who knows

def elapsed_json(request):
	first_group = [app for app in Jobapp.objects.filter(user=request.user) if 0 <= app.time_elapsed.days < 5]
	second_group = [app for app in Jobapp.objects.filter(user=request.user) if 5 < app.time_elapsed.days < 10]
	third_group = [app for app in Jobapp.objects.filter(user=request.user) if 10 < app.time_elapsed.days < 15]
	fourth_group = [app for app in Jobapp.objects.filter(user=request.user) if 15 < app.time_elapsed.days < 20]
	fifth_group = [app for app in Jobapp.objects.filter(user=request.user) if 20 < app.time_elapsed.days < 25]
	sixth_group = [app for app in Jobapp.objects.filter(user=request.user) if 25 < app.time_elapsed.days < 30]
	data = [len(first_group), len(second_group), len(third_group), len(fourth_group), len(fifth_group), len(sixth_group)]
	return JsonResponse(data, safe=False)

def canvas_json(request):
	jobapps = serializers.serialize("json", Jobapp.objects.filter(user=request.user), fields=('pipeline_status'))
	return JsonResponse(jobapps, safe=False) #this return could be redundant, who knows

def display_canvas(request):
	pipeline_individual_count = Jobapp.objects.filter(user=request.user)
	return render(request,'lfw/canvas.html', status_context(request))

def display_pipeline(request):
	return render(request,'lfw/pipeline.html', status_context(request))

def jobappform(request):
	if request.method == 'POST':
		form = Jobappform(user=request.user)
		app = Jobapp()
		for k, v in request.POST.items():
			print('label: {}'.format(k))
			print('value: {}'.format(v))
		app.name = request.POST.get('name')
		app.user = request.user
		app.company = request.POST.get('company')
		app.description = request.POST.get('description')
		app.url = request. POST.get('url')
		app.date_rolecreated = request.POST.get('date_rolecreated')
		print(request.POST.get('resume'))
		if request.POST.get('resume'):
			app.resume = Resume.objects.get(pk=request.POST.get('resume'))
		if request.POST.get('coverletter'): 
			app.coverletter = Coverletter.objects.get(pk=request.POST.get('coverletter'))
		app.save()
		# if form.is_valid():
		# 	print('addentry is valdi')
		# 	jobapp = form.save(commit=False)
		# 	jobapp.exuser = request.user 
		# 	jobapp.save()
		return redirect(reverse('lfw:index'))
	form = Jobappform(request.user)
	print(form)
	context = {'form': form}
	return render(request, 'lfw/jobappform.html', context)

def skills_input(request):
	if request.method == 'POST':
		form = Skills_input(request.POST)
		if form.is_valid():
			cl = form.save(commit=False)
			cl.user = request.user
			cl.save()
	form = Skills_input()
	context = {'form': form}
	return render(request, 'lfw/skills_input.html', context)	 

def add_res(request):
	if request.method == 'POST':
		form = Resumeform(request.POST)
		if form.is_valid():
			resume = form.save(commit=False)
			resume.user = request.user
			resume.save()
			return redirect(reverse('lfw:index'))
	form = Resumeform()
	context = {'form': form}
	return render(request, 'lfw/Res_form.html', context)	
#is this a context that's getting passed bewteen the front to middle or middle to back?

def add_cl(request):
	if request.method == 'POST':
		form = Clform(request.POST)
		if form.is_valid():
			cl = form.save(commit=False)
			cl.user = request.user
			cl.save()
			return redirect(reverse('lfw:index'))
	form = Clform()
	context = {'form': form}
	return render(request, 'lfw/cl_form.html', context)
#is this a context that's getting passed bewteen the front to middle or middle to back?

def clbuilder(request):
	if request.method == 'POST':
		form = CoverletterForm(request.user)
		coverletter = Coverletter()
		coverletter.user = request.user
		coverletter.clcopy = request.POST.get('coverlettercopy')
		coverletter.save()
		
		skills = request.POST.getlist('skills')
		for skillID in skills:
			skill = get_object_or_404(Skill, pk=skillID)
			coverletter.skills.add(skill)
		coverletter.save()
		
		jobappID = request.POST.get('jobapp')
		if jobappID and jobappID != "none":
			jobappID = int(jobappID)
			jobapp = get_object_or_404(Jobapp, pk=jobappID)
			jobapp.coverletter = coverletter
			jobapp.save()

	form = CoverletterForm(request.user)	

	coverlettertemplates = Coverlettertemplate.objects.filter(user=request.user)
	jobapps = Jobapp.objects.filter(user=request.user)
	skills = Skill.objects.filter(user=request.user)

	context = {
	'skills':skills,
	'jobapps':jobapps,
	'form': form,
	'coverlettertemplates' :coverlettertemplates,
	}
	return render(request, 'lfw/clbuilder.html', context)

def status_context(request):
	jobapps = Jobapp.objects.filter(user=request.user)
	prospects = jobapps.filter(pipeline_status='PS')
	reachedout = jobapps.filter(pipeline_status='RO')
	qualified = jobapps.filter(pipeline_status='QD')
	screening = jobapps.filter(pipeline_status='SN')
	context = {
		'jobapps': jobapps,
		'prospects' : prospects,
		'reachedout' : reachedout,
		'qualified' : qualified,
		'screening' : screening,
	}
	return context	

def jobapp_loader(request):
	jobapps = serializers.serialize("json", Jobapp.objects.filter(user=request.user))
	return JsonResponse(jobapps, safe=False)

def coverlettertemplate_loader(request):
	coverlettertemplates = serializers.serialize("json", Coverlettertemplate.objects.filter(user=request.user))
	return JsonResponse(coverlettertemplates, safe=False)

def cllistview(request):
	coverletter = Coverletter.objects.filter(user=request.user)
	context = {'coverletter' :coverletter,}
	return render(request, 'lfw/cllistview.html', context)
 
def jobapplistview(request):
	jobapp = Jobapp.objects.filter(user=request.user)
	context = {'jobapp' :jobapp,}
	return render(request, 'lfw/jobapplistview.html', context)

def edit_coverletter(request, pk):
	coverletter = get_object_or_404(Coverletter, pk=pk)

	if request.method == 'POST':
		form = CoverletterForm(request.user)
		coverletter.clcopy = request.POST.get('coverlettercopy')
		coverletter.save()
		
		skills = request.POST.getlist('skills')
		for skillID in skills:
			skill = get_object_or_404(Skill, pk=skillID)
			coverletter.skills.add(skill)
		coverletter.save()

		jobappID = request.POST.get('jobapp')
		if jobappID and jobappID != "none":
			jobappID = int(jobappID)
			jobapp = get_object_or_404(Jobapp, pk=jobappID)
			jobapp.coverletter = coverletter
			jobapp.save()

		return redirect('lfw:edit_coverletter', pk=pk)

	jobapps = Jobapp.objects.filter(user=request.user)
	form = CoverletterForm(request.user, initial={ 'coverlettercopy':coverletter.clcopy})
	return render(request, 'lfw/cleditor.html', {
		'form': form,
		'jobapps':jobapps,
		'pk': pk
	})

def edit_jobapp(request, pk):
	app = get_object_or_404(Jobapp, pk=pk)

	if request.method == 'POST':
		form = Jobappform(user=request.user)
		for k, v in request.POST.items():
			print('label: {}'.format(k))
			print('value: {}'.format(v))
		app.name = request.POST.get('name')
		app.user = request.user
		app.company = request.POST.get('company')
		app.description = request.POST.get('description')
		app.url = request. POST.get('url')
		app.date_rolecreated = request.POST.get('date_rolecreated')
		print(request.POST.get('resume'))
		if request.POST.get('resume'):
			app.resume = Resume.objects.get(pk=request.POST.get('resume'))
		if request.POST.get('coverletter'): 
			app.coverletter = Coverletter.objects.get(pk=request.POST.get('coverletter'))
		app.save()
		# if form.is_valid():
		# 	print('addentry is valdi')
		# 	jobapp = form.save(commit=False)
		# 	jobapp.exuser = request.user 
		# 	jobapp.save()
		return redirect(reverse('lfw:index'))

		return redirect('lfw:edit_jobapp', pk=pk)

	existing_app = {
		'name': app.name,
		'company': app.company,
		'description': app.description,
		'url': app.url,
		'date_rolecreated': app.date_rolecreated,
		'resume': app.resume,
		'coverletter': app.coverletter
	}
	form = Jobappform(request.user, initial=existing_app)
	return render(request, 'lfw/jobappeditor.html', {
		'form': form,
		'pk': pk
	})

def move_jobapp_status(request, pk):
	app = get_object_or_404(Jobapp, pk=pk)

	if app.pipeline_status == 'PS':
		app.pipeline_status = 'RO'
	
	elif app.pipeline_status == 'RO':
		app.pipeline_status = 'QD'
	
	elif app.pipeline_status == 'QD':
		app.pipeline_status = 'SN'
	app.save()
	return redirect('lfw:index')

def coverlettertemplateselect(request):
	coverletter = Coverletter.objects.filter(user=request.user)
	context = {'coverletter' : coverletter,}
	return request


# @login_required
# def index_view(request):
#    p = Model.objects.filter(user=request.user)
#    return render(request, 'app/index.html', {'objects': p})

# def all_forms(request):
# 	context = {}

lfwsite/lfw/templates/lfw/app_card.html
  <div class="card small">
      <div class="card-content">
        <span class="card-title activator grey-text text-darken-4">{{ jobapp.name }}<i class="material-icons right">more_vert</i></span>
        <p>{{ jobapp.company }}</p>
      </div>
      <div class="card-reveal">
        <span class="card-title grey-text text-darken-4">{{ jobapp.contact }}<i class="material-icons right">close</i></span>
        <p>{{ jobapp.description}}</p>
        <p>{{ jobapp.url}}</p>
      <div class="card-action">
       <a href="{% url 'lfw:jobappstatusupdate' pk=jobapp.pk %}" class="waves-effect waves-light btn-small">Move Forward</a>
      </div>
    </div>      
  </div>

lfwsite/lfw/templates/lfw/canvas.html
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.js"></script>
<div class="canvas-container">
    <canvas id="myChart"></canvas>
</div>
<script>

let jobappData = null

fetch('http://localhost:8000/canvas_json/')
  .then(function(response) {
    return response.json()
  })
  .then(function(myJson) {
    // console.log(JSON.stringify(myJson));
    displayBarChart(myJson)
  });

//I'm not 100% sure where I should be pulling things from and seeing where things go

function displayBarChart(jobData) {
    console.log(JSON.parse(jobData))
    jobData = JSON.parse(jobData)
    let labels = ['PS', 'RO', 'QD', 'SN']
    console.log(labels)
    let data = []
    for (let i=0; i<labels.length; ++i) {
        data.push(jobData.filter(e => e.fields.pipeline_status == labels[i]).length)
    }
    console.log(data)

    var ctx = document.getElementById("myChart");
    var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: ["Prospect", "Reachout", "Qualified", "Screenng"],
        datasets: [{
            label: '# of Apps',
            data: data,
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
        yAxes: [{
        ticks: {
        beginAtZero:true
                }
            }]
        }
    }
    });    
}

</script>

lfwsite/lfw/templates/lfw/cl_form.html
{% extends 'lfw/base.html' %}
{% load material_form %}

{% block content %}
<p>Submit Cover Letter! </p>

<form action="{% url 'lfw:add_cl'%}" method="post">
	{% csrf_token %}
    {% form form=form %}{% endform %}
	<button type="submit">Submit Cover Letter </button>
</form>

{% endblock %}

lfwsite/lfw/templates/lfw/cl_loader.html
<select id="dropdownselector" name="jobapp">
    <option value="none">Pick a Jobapp</option>
    {% for x in jobapps %}
    <option value="{{ x.id }}">{{ x.name }}</option>
    {% endfor %}
</select>

<div id = "clframe">
	<iframe id = "coverletter_window" frameborder="0" allowfullscreen  width=" 45%" height="400" style="box-shadow: 0 0 16px gray; margin: 10px;" name="joblisting" id="test"></iframe>
</div>

lfwsite/lfw/templates/lfw/cltexteditor.html
{% load material_form %}

<div class = "cltexteditor">
{% form form=form %}{% endform %}
</div>

lfwsite/lfw/templates/lfw/cltodo.html
{% load material_form %}
{% block content%}


<form action="{% url 'lfw:cltodo'%}" method="post">
	{% csrf_token %}
    {% form form=form %}{% endform %}
	<button type="submit">Add Coverletter Element </button>
</form>

<table id = "cltodotable" class = "responsive-table highlight">
	<thead>
		<tr>
			<th>user</th>
			<th>name</th>
			<th>copy</th>
			<th>coverletter</th>
		</tr>
	</thead>
	
{% for x in skills %}
	<tbody>
		<tr>
			<td>{{ x.user }}</td>
			<td>{{ x.name }}</td>
			<td>{{ x.copy }}</td>
			<td>{{ x.coverletter }}</td>
		</tr>
	</tbody>
{% endfor %}


</table>	
{% endblock %}

lfwsite/lfw/templates/lfw/coverlettertemplateselect.html
{% load material_form %}

<select id="coverletterselector" name="coverletterselector">
    <option value="none">Pick a Coverletter Template</option>
    {% for x in coverlettertemplates %}
    <option value="{{ x.id }}">{{ x.name }}</option>
    {% endfor %}
</select>

lfwsite/lfw/templates/lfw/display_elapsed.html
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.js"></script>
<div class="elapsed_container">
  <canvas id="elapsed"></canvas>
</div>
  
<script>

fetch('http://localhost:8000/elapsed_json/')
  .then(function(response) {
    return response.json()
  })
  .catch(errors => {
    console.log(errors)
  })
  .then(function(myJson) {
    // console.log(JSON.stringify(myJson));
    displayElapsedChart(myJson)
  });
// the last display chart hasn't gone into this yet

function displayElapsedChart(jobData) {
  var elapsedData = {
    labels: ["0-5", "5-10", "10-15", "15-20", "20-25", "25-30"],
    datasets: [{
      data: jobData,
      backgroundColor: [
        "rgba(0, 100, 255, 0.5)",
        "rgba(255, 0, 0, 0.5)",
        "rgba(100, 255, 0, 0.5)",
        "rgba(226, 226, 64, 0.5)",
        "rgba(170, 35, 245, 0.5)",
        "rgba(135, 35, 245, 0.5)",

      ],
    }]
  };

  var options = {
    legend: {
      postition:'right'
    },
    animation :{
      antimateRotate : false
    }

  };

  var ctx = document.getElementById("elapsed");
  var elapsed = new Chart(ctx, {
      type: 'polarArea',
      data: elapsedData,
      options: options
  });
}

</script>

lfwsite/lfw/templates/lfw/display_lagging.html
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.js"></script>
<div class="elapsed_container">
  <canvas id="lagging"></canvas>
</div>  
<script>
  var timeFormat = 'MM/DD/YYYY HH:mm';

  function newDate(days) {
      return moment().add(days, 'd').toDate();
    }
    function newDateString(days) {
      return moment().add(days, 'd').format(timeFormat);
    }


fetch('http://localhost:8000/elapsed_json/')
  .then(function(response) {
    return response.json()
  })
  .catch(errors => {
    console.log(errors)
  })
  .then(function(myJson) {
    // console.log(JSON.stringify(myJson));
    displayLaggingChart(myJson)
  });
// the last display chart hasn't gone into this yet

function displayLaggingChart(jobData) {
  var laggingData = {
    labels: ['ja1', 'ja2'],
    datasets: [{
      data: [jobData],
    }
]  };

  var options = {
    responsive: true,
    title:{
      display: true,
      text: "titletext"
    },

    scales: {
      xAxes: [{
        type: 'time',
        display: true,
        time: {
          displayFormats:{ day: 'MMM D'},
        }
      }]
  
    }
  };

  var ctx = document.getElementById("lagging");
  var lagging = new Chart(ctx, {
      type: 'horizontalBar',
      data: laggingData,
      options: options
  });
}
</script>

lfwsite/lfw/templates/lfw/jobappeditor.html
{% extends "lfw/base.html" %}
{% load material_form %}
{% include 'material/includes/material_css.html' %}
{% include 'material/includes/material_js.html' %}

{% block content %}
	
<form action="{% url 'lfw:edit_jobapp' pk=pk %}" method="post">
	{% csrf_token %}
    {% form form=form %}{% endform %}
	<button type="submit">SUBMIT JOBAPP EDIT</button>
</form>
{% endblock content %}

lfwsite/lfw/templates/lfw/jobappform.html
{% extends "lfw/base.html" %}
{% load material_form %}
{% include 'material/includes/material_css.html' %}
{% include 'material/includes/material_js.html' %}

{% block content %}
	
<form action="{% url 'lfw:jobappform'%}" method="post">
	{% csrf_token %}
    {% form form=form %}{% endform %}
	<button type="submit">NO TRUTHEXISTS! </button>
</form>
{% endblock content %}

lfwsite/lfw/templates/lfw/jobapplistview.html
{% extends 'lfw/base.html' %}
{% load static %}
{% block content%}


<h4>Job App List View</h4>
<table class = "responsive-table highlight">
	<thead>
		<tr>
			<th>name</th>
			<th>description</th>
			<th>company</th>
			<th>contact</th>
			<th>resume</th>
			<th>coverletter</th>
			<th>date_created</th>
		</tr>
	</thead>
	
{% for item in jobapp %}
	<tbody>
		<tr>
			<td><a href="{% url 'lfw:edit_jobapp' pk=item.pk%}">{{ item.name }}</a></td>
			<td>{{ item.description }}</td>
			<td>{{ item.company }}</td>
			<td>{{ item.contact }}</td>
			<td>{{ item.resume }}</td>
			<td><a href="{% url 'lfw:cllistview'%}">{{ item.coverletter }}</a></td>
			<td>{{ item.date_created }}</td>
		</tr>
	</tbody>
{% endfor %}
</table>	

{% endblock %}

lfwsite/lfw/templates/lfw/jobappview.html
{% block content%}

<h4>JobApps</h4>
<table class = "responsive-table highlight">
	<thead>
		<tr>
			<th>name</th>
			<th>description</th>
			<th>company</th>
			<th>contact</th>
			<th>coverletter</th>
			<th>date added</th>
		</tr>
	</thead>
	
{% for item in jobapps %}
	<tbody>
		<tr>
			<td><a href="{% url 'lfw:edit_jobapp' pk=item.pk%}">{{ item.name }}</a></td>
			<td>{{ item.description }}</td>
			<td>{{ item.company }}</td>
			<td>{{ item.contact }}</td>
			<td><a href="{% url 'lfw:cllistview'%}">{{ item.coverletter }}</a></td>
			<td>{{ item.date_created }}</td>
		</tr>
	</tbody>
{% endfor %}
</table>	
{% endblock %}

lfwsite/lfw/templates/lfw/skills_input.html
{% extends "lfw/base.html" %}
{% load material_form %}
{% block content%}

<form action="{% url 'lfw:skills_input'%}" method="post">
	{% csrf_token %}
    {% form form=form %}{% endform %}
	<button type="submit">Add Skill </button>
</form>

{% endblock %}